#!/bin/sh
## 
## This script pulls information generated by the Adobe license expiry calculator script stored in /tmp/AdobeCC2017Serial/checkAdobeExpiredLicenses_result.txt
## Date is displayed YYYYMMDD format
## rrs384
#
if [ -f /tmp/AdobeCC2017Serial/checkAdobeExpiredLicenses_result.txt ]; then
	param=(`grep -R 'Creative' /tmp/AdobeCC2017Serial/checkAdobeExpiredLicenses_result.txt | awk '{print $3}'`)
	if (  [[ !  -z  $param  ]] ); then
    	echo "<result>$param</result>"
	else
    	echo "<result>00000000</result>"
	fi
fi